// src/components/DiffViewer.svelte
<script>
    // import { onMount, onDestroy } from "svelte";
    import "diff2html/bundles/css/diff2html.min.css";
    import * as Diff2Html from "diff2html"; //TODO: Find a way to use local resources without NPM if possible?
    // const Diff2Html = {};
    // Diff2Html.html = ()=>{console.log("Diff2Html: The lib is missing. Need to check.");}
    // Import necessary modules
    // import '../assets/diff2html.min.css';
    // import * as Diff2Html from '../assets/diff2html.min.js';

    // Define component props
    export let diffString;

    // Reactive variable to store the rendered diff HTML
    let renderedDiff = "";

    // Function to render the diff
    const showDiff = () => {
        const configuration = {
            drawFileList: true,
            fileListToggle: false,
            fileListStartVisible: false,
            fileContentToggle: false,
            matching: "lines",
            outputFormat: "side-by-side",
            synchronisedScroll: true,
            highlight: true,
            renderNothingWhenEmpty: false,
        };

        // debugger;
        // const diff = $diffString;

        renderedDiff = diffString
            ? Diff2Html.html(diffString, configuration)
            : "";
    };

    // Reactive statement to handle updates
    $: {
        // debugger;
        // const diff = $diffString;
        if (diffString === "Binary file") {
            renderedDiff = `<h3>Preview: ${diffString}</h3>`;
        } else if (diffString) {
            showDiff();
        } else {
            renderedDiff = "<h3>Preview: No Changes</h3>";
        }
    }
</script>

<!-- Render the diff HTML -->
<div>
    {@html renderedDiff}
</div>

<style>
    /* TODO: This is a hack to hide the title of the diff viewer. This should be fixed. */
    :global(.d2h-file-list-wrapper) {
        display: none;
    }
</style>

// src/components/DiffViewer.vue
<template>
    <div v-html="renderedDiff" />
</template>

<script setup>
// Import necessary modules
// import '../assets/diff2html.min.css';
// import * as Diff2Html from '../assets/diff2html.min.js';
import { ref, watch } from 'vue';
import 'diff2html/bundles/css/diff2html.min.css';
import * as Diff2Html from 'diff2html'; //TODO: Find a way to use local resources without NPM if possible?

// Define component props
const props = defineProps({
    diffString: String
});

// Ref to store rendered diff HTML
const renderedDiff = ref('');

// Define a method to render the diff
const showDiff = () => {
    const configuration = {
        drawFileList: true,
        fileListToggle: false,
        fileListStartVisible: false,
        fileContentToggle: false,
        matching: 'lines',
        outputFormat: 'side-by-side',
        synchronisedScroll: true,
        highlight: true,
        renderNothingWhenEmpty: false,
    };
    // debugger;
    renderedDiff.value = props.diffString ? Diff2Html.html(props.diffString, configuration) : '';
};

// Watch for changes to diffString and call showDiff when it changes
watch(() => props.diffString, (newVal) => {
    // debugger
    if (newVal === "Binary file") {
        renderedDiff.value = newVal;
    }
    else if (newVal) {
        showDiff();
    }
    else {
        renderedDiff.value = "No Changes";//TODO: Need to handle a situation when a file is already staged
    }
}, { immediate: true });
</script>


<style scoped></style>
